name: themoviedb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  provider: ^6.0.3
  http: ^0.13.4
  connectivity_plus: ^2.3.5
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  flutter_cache: ^0.1.0
  cached_network_image: ^3.2.1
  sqflite: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

